### ISSUE TITLE
feedback to Readme.md in the "rpi" directory

### ISSUE THREAD

**Issue by masa-ito4github** [RoboCup-SSL/ssl-remote-control#37]
If we use [Raspberry Pi Imager](https://www.raspberrypi.com/software/) to install an RPi OS into a microSD card, we can setup username, password, hostname and ssh in the advanced options (a gear icon) before writing.

**Comment by masa-ito4github** [comment]
Before running the bootstrap script, we need to correct date and time such that APT commands work properly, for example, by executing the following command:
```
sudo date --set="2022/07/05 11:38:00"
```

**Comment by masa-ito4github** [comment]
In the bootstrap script and .xinitrc, "chromium-browser" should be replaced with "chromium".

**Comment by g3force** [comment]
I've updated the documentation regarding the rpi-imager.

The time and apt issue is probably related to your network setup and should work in general.

Also, `chromium-browser` is correct and works if the apt sources were updated correctly ;)
